// Generated by scripts/icons/export.mjs from @phosphor-icons/react 2.1.10. Do not edit.
import spriteMarkup from './sprite.svg?raw';

/** Every symbol in the sprite, as `<glyph-kebab>-<weight>`. */
export const ICON_SYMBOL_IDS = new Set<string>([
  'arrow-left-regular',
  'arrows-clockwise-regular',
  'barcode-regular',
  'calendar-check-regular',
  'camera-regular',
  'caret-down-regular',
  'caret-left-regular',
  'caret-right-regular',
  'caret-up-regular',
  'check-bold',
  'check-regular',
  'check-circle-regular',
  'clock-regular',
  'cooking-pot-bold',
  'cooking-pot-regular',
  'drop-regular',
  'house-bold',
  'house-regular',
  'image-square-regular',
  'info-regular',
  'list-regular',
  'magnifying-glass-bold',
  'magnifying-glass-regular',
  'minus-bold',
  'minus-regular',
  'pencil-simple-regular',
  'plus-bold',
  'plus-regular',
  'sliders-horizontal-regular',
  'squares-four-regular',
  'warning-regular',
  'warning-circle-regular',
  'x-regular',
]);

/** The Phosphor package version the sprite was exported from. */
export const ICON_SOURCE = '@phosphor-icons/react@2.1.10';

export { spriteMarkup };
