/**
 * Exports the Phosphor glyphs the product UI actually renders into `src/assets/icons/`:
 * one SVG per (glyph, weight) pair and one sprite of `<symbol>`s the shared `Icon`
 * component references through `<use>`. Every path comes verbatim from the installed
 * `@phosphor-icons/react` package (its own `defs/*.es.js` modules), so the drawn glyphs
 * stay the official family at the official weights — nothing is redrawn, simplified or
 * added, and nothing outside the product's usage is copied.
 *
 *   node scripts/icons/export.mjs          # regenerate
 *   node scripts/icons/export.mjs --check  # fail when the committed output is stale
 *
 * Usage is discovered from the source: every glyph imported from `@phosphor-icons/react`
 * by a non-story, non-catalogue module is exported at `regular`; a glyph is also exported
 * at `bold` when a production file renders it with `weight="bold"` (a dynamic
 * `weight={… 'bold' …}` on an `icon={icon}` slot marks every glyph that file imports).
 * The `fill` weight is not used by the product and is therefore not exported.
 */
import { createRequire } from 'node:module';
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const srcDir = path.join(root, 'src');
const outDir = path.join(srcDir, 'assets', 'icons');
const require = createRequire(import.meta.url);
const pkgDir = path.dirname(require.resolve('@phosphor-icons/react/package.json'));
const pkg = JSON.parse(readFileSync(path.join(pkgDir, 'package.json'), 'utf8'));
const check = process.argv.includes('--check');

// --- 1. Discover usage ---------------------------------------------------------------

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const file = path.join(dir, name);
    if (statSync(file).isDirectory()) {
      if (name === 'assets' || name === 'docs' || name === 'storybook') continue;
      walk(file, out);
    } else if (/\.(tsx?|mts)$/.test(name) && !/\.stories\.tsx$/.test(name) && !/\.test\.tsx?$/.test(name) && name !== 'catalogue.ts') {
      out.push(file);
    }
  }
  return out;
}

const usage = new Map(); // name -> Set(weights)
for (const file of walk(srcDir)) {
  const text = readFileSync(file, 'utf8');
  const imports = [...text.matchAll(/import\s*\{([^}]*)\}\s*from\s*'@phosphor-icons\/react'/g)].flatMap((m) =>
    m[1]
      .split(',')
      .map((s) => s.trim())
      .filter((s) => s && !s.startsWith('type '))
      .map((s) => s.replace(/\s+as\s+\w+$/, '')),
  );
  if (imports.length === 0) continue;
  for (const name of imports) {
    if (!usage.has(name)) usage.set(name, new Set(['regular']));
  }
  for (const line of text.split('\n')) {
    if (!/weight=/.test(line) || !/bold/.test(line)) continue;
    // A dynamic slot (`icon={icon}`) marks every glyph the file imports; otherwise every
    // imported glyph named on that line (including inside a ternary) is rendered bold.
    const names = /icon=\{[a-z]\w*\}/.test(line) ? imports : imports.filter((name) => new RegExp(`\\b${name}\\b`).test(line));
    for (const name of names) usage.get(name)?.add('bold');
  }
}

// --- 2. Read the official definitions ---------------------------------------------------

const kebab = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** Serialises the React element tree Phosphor stores per weight into SVG markup. */
function serialise(node) {
  if (node === null || node === undefined || node === false) return '';
  if (Array.isArray(node)) return node.map(serialise).join('');
  if (typeof node === 'string') return node;
  const { type, props } = node;
  const children = serialise(props?.children);
  if (typeof type !== 'string') return children; // Fragment
  const attrs = Object.entries(props ?? {})
    .filter(([key]) => key !== 'children')
    .map(([key, value]) => ` ${key}="${String(value)}"`)
    .join('');
  return children ? `<${type}${attrs}>${children}</${type}>` : `<${type}${attrs}/>`;
}

const entries = [];
for (const name of [...usage.keys()].sort()) {
  const defPath = path.join(pkgDir, 'dist', 'defs', `${name}.es.js`);
  if (!existsSync(defPath)) throw new Error(`No Phosphor definition for ${name}`);
  const mod = await import(pathToFileURL(defPath).href);
  const weights = mod.default;
  for (const weight of [...usage.get(name)].sort()) {
    const element = weights.get(weight);
    if (!element) throw new Error(`${name} has no ${weight} weight`);
    entries.push({ name, weight, id: `${kebab(name)}-${weight}`, body: serialise(element) });
  }
}

// --- 3. Emit ------------------------------------------------------------------------------

const header = `<!-- Generated by scripts/icons/export.mjs from @phosphor-icons/react ${pkg.version} (MIT, see LICENSE). Do not edit. -->`;
const files = new Map();
files.set(
  'sprite.svg',
  `${header}\n<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n${entries.map((e) => `  <symbol id="${e.id}" viewBox="0 0 256 256">${e.body}</symbol>`).join('\n')}\n</svg>\n`,
);
for (const e of entries) {
  files.set(`svg/${e.id}.svg`, `${header}\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor">${e.body}</svg>\n`);
}
files.set(
  'index.ts',
  `// Generated by scripts/icons/export.mjs from @phosphor-icons/react ${pkg.version}. Do not edit.
import spriteMarkup from './sprite.svg?raw';

/** Every symbol in the sprite, as \`<glyph-kebab>-<weight>\`. */
export const ICON_SYMBOL_IDS = new Set<string>([
${entries.map((e) => `  '${e.id}',`).join('\n')}
]);

/** The Phosphor package version the sprite was exported from. */
export const ICON_SOURCE = '@phosphor-icons/react@${pkg.version}';

export { spriteMarkup };
`,
);
files.set(
  'README.md',
  `# Product icons

Generated by \`scripts/icons/export.mjs\` from the installed \`@phosphor-icons/react\` (${pkg.version}, MIT — see \`LICENSE\`). Contains only the glyphs the product UI renders, at the weights it renders them (regular everywhere; bold where a component passes \`weight="bold"\`). The shared \`Icon\` component renders these symbols through \`<use>\`; a glyph that is not in the sprite (Storybook's icon catalogue, for instance) still renders through the React package. Regenerate with \`npm run icons:build\`; \`npm run icons:check\` fails when this folder is stale.

| Symbol | Glyph | Weight |
| --- | --- | --- |
${entries.map((e) => `| \`${e.id}\` | ${e.name} | ${e.weight} |`).join('\n')}
`,
);
files.set('LICENSE', readFileSync(path.join(pkgDir, 'LICENSE'), 'utf8'));

if (check) {
  const stale = [];
  for (const [rel, content] of files) {
    const file = path.join(outDir, rel);
    if (!existsSync(file) || readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== content) stale.push(rel);
  }
  const extra = existsSync(path.join(outDir, 'svg')) ? readdirSync(path.join(outDir, 'svg')).filter((f) => !files.has(`svg/${f}`)) : [];
  if (stale.length || extra.length) {
    console.error(`icons: stale output — ${[...stale, ...extra.map((f) => `svg/${f} (unused)`)].join(', ')}`);
    process.exit(1);
  }
  console.log(`icons: ${entries.length} symbols from ${usage.size} glyphs; generated output is current.`);
} else {
  rmSync(path.join(outDir, 'svg'), { recursive: true, force: true });
  mkdirSync(path.join(outDir, 'svg'), { recursive: true });
  for (const [rel, content] of files) writeFileSync(path.join(outDir, rel), content);
  console.log(`icons: wrote ${entries.length} symbols from ${usage.size} glyphs to ${path.relative(root, outDir)}.`);
}
