/**
 * Storybook-only catalogue of official Phosphor glyphs relevant to Portion.
 *
 * This file is deliberately NOT exported from the design-system public entry point:
 * it exists for discovery and documentation. Product code imports the specific glyph it
 * needs from `@phosphor-icons/react` and renders it through `Icon`.
 *
 * Every export name below was verified against @phosphor-icons/react 2.1.10 on
 * 2026-09-02 (`scripts` inspection); names are the package's JavaScript identifiers.
 */
import {
  Aperture,
  Archive,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowsClockwise,
  ArrowsInSimple,
  ArrowsOutSimple,
  Article,
  Avocado,
  Barbell,
  Barcode,
  Basket,
  BatteryWarning,
  BowlFood,
  Bread,
  Calculator,
  CalendarBlank,
  CalendarCheck,
  Camera,
  CameraRotate,
  CameraSlash,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Carrot,
  Check,
  CheckCircle,
  CheckSquare,
  Cheese,
  Circle,
  CircleNotch,
  Clipboard,
  ClipboardText,
  Clock,
  ClockClockwise,
  ClockCounterClockwise,
  CloudSlash,
  Coffee,
  Cookie,
  CookingPot,
  Copy,
  CornersIn,
  CornersOut,
  Crosshair,
  CrosshairSimple,
  Cube,
  DeviceMobile,
  Dot,
  DotOutline,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Drop,
  Egg,
  Export,
  Eye,
  EyeSlash,
  FileText,
  Fire,
  Fish,
  Flask,
  FloppyDisk,
  FolderOpen,
  ForkKnife,
  FrameCorners,
  Funnel,
  FunnelSimple,
  Grains,
  GridFour,
  Hamburger,
  HandTap,
  Hash,
  Heartbeat,
  Hourglass,
  House,
  IceCream,
  Image,
  ImageBroken,
  Info,
  Keyboard,
  Leaf,
  Lightbulb,
  Link,
  List,
  ListBullets,
  Lock,
  MagnifyingGlass,
  Microphone,
  Minus,
  Note,
  NotePencil,
  Orange,
  Package,
  Pencil,
  PencilSimple,
  Pepper,
  Percent,
  Pizza,
  Plant,
  Plus,
  Prohibit,
  QrCode,
  Question,
  RadioButton,
  Receipt,
  Ruler,
  Scales,
  Scan,
  ShareNetwork,
  ShieldCheck,
  ShieldWarning,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Sparkle,
  Spinner,
  SpinnerGap,
  Square,
  Tag,
  Target,
  TextAa,
  TextAlignLeft,
  Timer,
  Trash,
  UploadSimple,
  Warning,
  WarningCircle,
  WifiHigh,
  WifiSlash,
  X,
  XCircle,
} from '@phosphor-icons/react';
import type { Icon as PhosphorIcon } from '@phosphor-icons/react';

export type IconGroup =
  | 'Navigation'
  | 'Entry methods'
  | 'Actions'
  | 'Status and feedback'
  | 'Selection'
  | 'Time'
  | 'Food and nutrition'
  | 'Content and data';

export interface CatalogueEntry {
  /** JavaScript export name in @phosphor-icons/react. */
  name: string;
  icon: PhosphorIcon;
  group: IconGroup;
  /** Where Portion uses or could use it; kept short and honest. */
  use: string;
}

const entry = (name: string, icon: PhosphorIcon, group: IconGroup, use: string): CatalogueEntry => ({ name, icon, group, use });

export const iconCatalogue: readonly CatalogueEntry[] = [
  // Navigation
  entry('House', House, 'Navigation', 'Home destination; bold when selected'),
  entry('Calculator', Calculator, 'Navigation', 'Calculation remains a capability, not a navigation destination'),
  entry('MagnifyingGlass', MagnifyingGlass, 'Navigation', 'Search destination and search fields'),
  entry('CookingPot', CookingPot, 'Navigation', 'Recipes destination; bold when selected'),
  entry('Plus', Plus, 'Navigation', 'Add food — the trailing action in the bottom row'),
  entry('ArrowLeft', ArrowLeft, 'Navigation', 'Back in focused flows'),
  entry('X', X, 'Navigation', 'Close a sheet or dialog; clear a field'),
  entry('CaretDown', CaretDown, 'Navigation', 'Disclosure and unit selector'),
  entry('CaretUp', CaretUp, 'Navigation', 'Collapse disclosed content'),
  entry('CaretRight', CaretRight, 'Navigation', 'Row leads to another screen'),
  entry('CaretLeft', CaretLeft, 'Navigation', 'Reverse of CaretRight'),
  entry('ArrowRight', ArrowRight, 'Navigation', 'Forward relation in explanations'),
  entry('ArrowSquareOut', ArrowSquareOut, 'Navigation', 'Opens system settings or an external page'),
  entry('DotsThree', DotsThree, 'Navigation', 'Overflow of secondary actions'),
  entry('DotsThreeVertical', DotsThreeVertical, 'Navigation', 'Vertical overflow variant'),
  entry('List', List, 'Navigation', 'List view'),
  entry('GridFour', GridFour, 'Navigation', 'Grid view'),

  // Entry methods
  entry('Barcode', Barcode, 'Entry methods', 'Scan barcode method and scanner state'),
  entry('Camera', Camera, 'Entry methods', 'Take a photo method and capture'),
  entry('PencilSimple', PencilSimple, 'Entry methods', 'Enter manually; edit an entered value'),
  entry('Pencil', Pencil, 'Entry methods', 'Alternative edit glyph'),
  entry('Scan', Scan, 'Entry methods', 'Scanning viewport framing'),
  entry('QrCode', QrCode, 'Entry methods', 'Code-type explanation'),
  entry('CameraSlash', CameraSlash, 'Entry methods', 'Camera unavailable or access denied'),
  entry('CameraRotate', CameraRotate, 'Entry methods', 'Switch camera'),
  entry('Aperture', Aperture, 'Entry methods', 'Shutter'),
  entry('Image', Image, 'Entry methods', 'Captured image or recipe photo'),
  entry('ImageBroken', ImageBroken, 'Entry methods', 'Image failed to load — content stays'),
  entry('Keyboard', Keyboard, 'Entry methods', 'Manual entry hint'),
  entry('Microphone', Microphone, 'Entry methods', 'Reserved; no voice entry in scope'),
  entry('FrameCorners', FrameCorners, 'Entry methods', 'Scan region corners'),
  entry('Crosshair', Crosshair, 'Entry methods', 'Aim guidance'),
  entry('CrosshairSimple', CrosshairSimple, 'Entry methods', 'Aim guidance, lighter'),
  entry('Target', Target, 'Entry methods', 'Aim guidance, filled centre'),

  // Actions
  entry('Check', Check, 'Actions', 'Criterion met; confirm; selected option'),
  entry('CheckCircle', CheckCircle, 'Actions', 'Defined success outcome'),
  entry('Minus', Minus, 'Actions', 'Decrease in a stepper'),
  entry('Trash', Trash, 'Actions', 'Discard a draft'),
  entry('Copy', Copy, 'Actions', 'Copy a value'),
  entry('ArrowCounterClockwise', ArrowCounterClockwise, 'Actions', 'Reset a draft'),
  entry('ArrowClockwise', ArrowClockwise, 'Actions', 'Retry a request'),
  entry('ArrowsClockwise', ArrowsClockwise, 'Actions', 'Refresh results'),
  entry('Funnel', Funnel, 'Actions', 'Filters entry'),
  entry('FunnelSimple', FunnelSimple, 'Actions', 'Filters entry, lighter'),
  entry('SlidersHorizontal', SlidersHorizontal, 'Actions', 'Filters entry — the product default'),
  entry('Sliders', Sliders, 'Actions', 'Vertical sliders variant'),
  entry('Eye', Eye, 'Actions', 'Show additional nutrition'),
  entry('EyeSlash', EyeSlash, 'Actions', 'Hide additional nutrition'),
  entry('Export', Export, 'Actions', 'Reserved; no sharing in scope'),
  entry('ShareNetwork', ShareNetwork, 'Actions', 'Reserved; no sharing in scope'),
  entry('DownloadSimple', DownloadSimple, 'Actions', 'Reserved'),
  entry('UploadSimple', UploadSimple, 'Actions', 'Choose an existing photo'),
  entry('FloppyDisk', FloppyDisk, 'Actions', 'Not used — no save step in the current flow'),
  entry('NotePencil', NotePencil, 'Actions', 'Edit entered reference data'),
  entry('Note', Note, 'Actions', 'Note or description'),
  entry('Link', Link, 'Actions', 'Source link'),
  entry('CornersOut', CornersOut, 'Actions', 'Expand'),
  entry('CornersIn', CornersIn, 'Actions', 'Collapse'),
  entry('ArrowsOutSimple', ArrowsOutSimple, 'Actions', 'Expand, simple'),
  entry('ArrowsInSimple', ArrowsInSimple, 'Actions', 'Collapse, simple'),
  entry('HandTap', HandTap, 'Actions', 'Tap guidance in onboarding-free help'),

  // Status and feedback
  entry('Info', Info, 'Status and feedback', 'Information message; estimate explanation'),
  entry('Warning', Warning, 'Status and feedback', 'Warning message'),
  entry('WarningCircle', WarningCircle, 'Status and feedback', 'Error message and invalid field'),
  entry('XCircle', XCircle, 'Status and feedback', 'Failed outcome'),
  entry('Question', Question, 'Status and feedback', 'Contextual help'),
  entry('Lightbulb', Lightbulb, 'Status and feedback', 'Suggestion'),
  entry('Prohibit', Prohibit, 'Status and feedback', 'Unsupported action'),
  entry('ShieldCheck', ShieldCheck, 'Status and feedback', 'Permission granted'),
  entry('ShieldWarning', ShieldWarning, 'Status and feedback', 'Permission needed'),
  entry('Lock', Lock, 'Status and feedback', 'Access restricted'),
  entry('CircleNotch', CircleNotch, 'Status and feedback', 'Progress glyph'),
  entry('Spinner', Spinner, 'Status and feedback', 'Progress glyph'),
  entry('SpinnerGap', SpinnerGap, 'Status and feedback', 'Progress glyph'),
  entry('WifiSlash', WifiSlash, 'Status and feedback', 'Network unavailable'),
  entry('WifiHigh', WifiHigh, 'Status and feedback', 'Network available'),
  entry('CloudSlash', CloudSlash, 'Status and feedback', 'Service unavailable'),
  entry('BatteryWarning', BatteryWarning, 'Status and feedback', 'Reserved'),

  // Selection
  entry('CheckSquare', CheckSquare, 'Selection', 'Checked option'),
  entry('Square', Square, 'Selection', 'Unchecked option'),
  entry('RadioButton', RadioButton, 'Selection', 'Selected radio'),
  entry('Circle', Circle, 'Selection', 'Unselected radio'),
  entry('Dot', Dot, 'Selection', 'Selected indicator'),
  entry('DotOutline', DotOutline, 'Selection', 'Unselected indicator'),

  // Time
  entry('Clock', Clock, 'Time', 'Preparation time'),
  entry('Timer', Timer, 'Time', 'Cooking timer metadata'),
  entry('Hourglass', Hourglass, 'Time', 'Pending'),
  entry('ClockCounterClockwise', ClockCounterClockwise, 'Time', 'Reserved — no history in scope'),
  entry('ClockClockwise', ClockClockwise, 'Time', 'Reserved'),
  entry('CalendarBlank', CalendarBlank, 'Time', 'Reserved — no diary in scope'),
  entry('CalendarCheck', CalendarCheck, 'Time', 'Reserved'),

  // Food and nutrition
  entry('ForkKnife', ForkKnife, 'Food and nutrition', 'Serving and dish'),
  entry('BowlFood', BowlFood, 'Food and nutrition', 'Dish placeholder'),
  entry('Fish', Fish, 'Food and nutrition', 'Dietary preference example'),
  entry('Carrot', Carrot, 'Food and nutrition', 'Vegetable'),
  entry('Leaf', Leaf, 'Food and nutrition', 'Vegetarian preference'),
  entry('Plant', Plant, 'Food and nutrition', 'Vegan preference'),
  entry('Grains', Grains, 'Food and nutrition', 'Grains'),
  entry('Drop', Drop, 'Food and nutrition', 'Liquid'),
  entry('Fire', Fire, 'Food and nutrition', 'Energy — never as a warning treatment'),
  entry('Coffee', Coffee, 'Food and nutrition', 'Drink'),
  entry('Egg', Egg, 'Food and nutrition', 'Ingredient'),
  entry('Bread', Bread, 'Food and nutrition', 'Ingredient'),
  entry('Cheese', Cheese, 'Food and nutrition', 'Ingredient'),
  entry('Pizza', Pizza, 'Food and nutrition', 'Dish'),
  entry('Hamburger', Hamburger, 'Food and nutrition', 'Dish'),
  entry('Cookie', Cookie, 'Food and nutrition', 'Snack'),
  entry('IceCream', IceCream, 'Food and nutrition', 'Dessert'),
  entry('Orange', Orange, 'Food and nutrition', 'Fruit'),
  entry('Avocado', Avocado, 'Food and nutrition', 'Fruit'),
  entry('Pepper', Pepper, 'Food and nutrition', 'Vegetable'),
  entry('Scales', Scales, 'Food and nutrition', 'Reference basis'),
  entry('Ruler', Ruler, 'Food and nutrition', 'Measurement'),
  entry('Percent', Percent, 'Food and nutrition', 'Not used — no daily-value percentages'),
  entry('Flask', Flask, 'Food and nutrition', 'Nutrient group'),
  entry('Heartbeat', Heartbeat, 'Food and nutrition', 'Not used — no health scoring'),
  entry('Barbell', Barbell, 'Food and nutrition', 'Protein criterion illustration'),

  // Content and data
  entry('Article', Article, 'Content and data', 'Instructions'),
  entry('TextAlignLeft', TextAlignLeft, 'Content and data', 'Description'),
  entry('TextAa', TextAa, 'Content and data', 'Text size'),
  entry('ListBullets', ListBullets, 'Content and data', 'Ingredients list'),
  entry('Receipt', Receipt, 'Content and data', 'Nutrition table'),
  entry('ClipboardText', ClipboardText, 'Content and data', 'Reference data'),
  entry('Clipboard', Clipboard, 'Content and data', 'Reference data'),
  entry('FileText', FileText, 'Content and data', 'Source document'),
  entry('FolderOpen', FolderOpen, 'Content and data', 'Reserved — no collections in scope'),
  entry('Archive', Archive, 'Content and data', 'Reserved'),
  entry('Tag', Tag, 'Content and data', 'Dietary tag'),
  entry('Hash', Hash, 'Content and data', 'Count'),
  entry('Cube', Cube, 'Content and data', 'Product'),
  entry('Package', Package, 'Content and data', 'Packaged product'),
  entry('Basket', Basket, 'Content and data', 'Reserved'),
  entry('ShoppingCart', ShoppingCart, 'Content and data', 'Reserved'),
  entry('DeviceMobile', DeviceMobile, 'Content and data', 'Platform mapping'),
  entry('Sparkle', Sparkle, 'Content and data', 'Photo suggestion — labelled as a suggestion'),
];

export const iconGroups: readonly IconGroup[] = [
  'Navigation',
  'Entry methods',
  'Actions',
  'Status and feedback',
  'Selection',
  'Time',
  'Food and nutrition',
  'Content and data',
];
